[workspace]
members = ["projects/*"]
default-members = [
    "projects/flatten-files",
    "projects/resource-path",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
